AWSTemplateFormatVersion: '2010-09-09'
Description: GitHub Actions OIDC Setup for SAM Deployments

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub username
    Default: franserr2288
  
  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: lovelettertoLA

Resources:
  GitHubActionsSAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GitHubActionsSAMDeployPolicy
      Description: Core SAM deployment permissions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: FullS3Access
            Effect: Allow
            Action: 's3:*'
            Resource: '*'
          
          - Sid: FullLambdaAccess
            Effect: Allow
            Action: 'lambda:*'
            Resource: '*'
          
          - Sid: CloudFormationAccess
            Effect: Allow
            Action:
              - 'cloudformation:*'
            Resource: '*'
          
          - Sid: IAMRoleManagement
            Effect: Allow
            Action:
              - 'iam:CreateRole'
              - 'iam:DeleteRole'
              - 'iam:GetRole'
              - 'iam:PassRole'
              - 'iam:AttachRolePolicy'
              - 'iam:DetachRolePolicy'
              - 'iam:PutRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'iam:GetRolePolicy'
              - 'iam:ListRolePolicies'
              - 'iam:ListAttachedRolePolicies'
              - 'iam:UpdateAssumeRolePolicy'
              - 'iam:TagRole'
              - 'iam:UntagRole'
            Resource:
              - 'arn:aws:iam::*:role/*-LambdaExecutionRole-*'
              - 'arn:aws:iam::*:role/*-FunctionRole-*'
              - 'arn:aws:iam::*:role/*Function*Role*'
              - 'arn:aws:iam::*:role/*LambdaRole*'
              - 'arn:aws:iam::*:role/IngestionSchedulerRole'
              - 'arn:aws:iam::*:role/IngestionLambdaRole'
          
          - Sid: IAMPolicyManagement
            Effect: Allow
            Action:
              - 'iam:CreatePolicy'
              - 'iam:DeletePolicy'
              - 'iam:GetPolicy'
              - 'iam:GetPolicyVersion'
              - 'iam:ListPolicyVersions'
              - 'iam:CreateServiceLinkedRole'
            Resource: '*'
          
          - Sid: LogsAccess
            Effect: Allow
            Action:
              - 'logs:*'
            Resource: '*'
          
          - Sid: APIGatewayAccess
            Effect: Allow
            Action:
              - 'apigateway:*'
              - 'apigatewayv2:*'
            Resource: '*'

  GitHubActionsAWSServicesPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: GitHubActionsAWSServicesPolicy
      Description: AWS services access for SAM deployment
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: EventBridgeAccess
            Effect: Allow
            Action:
              - 'events:*'
              - 'scheduler:*'
            Resource: '*'
          
          - Sid: SQSAccess
            Effect: Allow
            Action: 'sqs:*'
            Resource: '*'
          
          - Sid: SNSAccess
            Effect: Allow
            Action: 'sns:*'
            Resource: '*'
          
          - Sid: DynamoDBAccess
            Effect: Allow
            Action: 'dynamodb:*'
            Resource: '*'
          
          - Sid: ECRAccess
            Effect: Allow
            Action: 'ecr:*'
            Resource: '*'
          
          - Sid: SecretsAndParametersAccess
            Effect: Allow
            Action:
              - 'secretsmanager:*'
              - 'ssm:*'
            Resource: '*'
          
          - Sid: STSAccess
            Effect: Allow
            Action: 'sts:*'
            Resource: '*'
          
          - Sid: WAFAccess
            Effect: Allow
            Action: 'wafv2:*'
            Resource: '*'
          
          - Sid: CognitoAccess
            Effect: Allow
            Action:
              - 'cognito-idp:*'
              - 'cognito-identity:*'
            Resource: '*'

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsSAMDeployRole
      Description: Role for GitHub Actions to deploy SAM applications
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': 
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
                  - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:environment:dev'
      ManagedPolicyArns:
        - !Ref GitHubActionsSAMPolicy
        - !Ref GitHubActionsAWSServicesPolicy