AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB table creation


Resources:
  JobQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: job-queue
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: batch_id
          AttributeType: S
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: batch_id
          KeyType: HASH
        - AttributeName: job_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: status-index
          KeySchema:
            - AttributeName: batch_id
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY

  JobQueueTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /shared/job-queue-table
      Type: String
      Value: !Ref JobQueueTable
      Description: DynamoDB job queue table name