AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy API Gateway

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  
  ThrottleRateLimit:
    Type: Number
    Default: 10
    Description: Requests per second
  
  ThrottleBurstLimit:
    Type: Number
    Default: 20
    Description: Max concurrent requests

Resources: 
  ApiGateway:
    Type: AWS::Serverless::Api
    # DependsOn:
    #   - ApiAccessLogGroup
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: "{{resolve:ssm:/shared/cognito/user-pool-arn}}"
            Identity:
              Header: Authorization
        ApiKeyRequired: false  # per-endpoint in app-component templates
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingRateLimit: !Ref ThrottleRateLimit
          ThrottlingBurstLimit: !Ref ThrottleBurstLimit
          # LoggingLevel: INFO
          # DataTraceEnabled: true
          MetricsEnabled: true
      # AccessLogSetting:
      #   DestinationArn: !GetAtt ApiAccessLogGroup.Arn
      #   Format: '$context.requestId $context.extendedRequestId $context.identity.sourceIp $context.requestTime $context.httpMethod $context.routeKey $context.status $context.protocol $context.responseLength'
      Tags:
        Environment: !Ref Environment
  
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: health_check.handler
      Runtime: python3.12
      CodeUri: .
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref ApiGateway

  # ApiAccessLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub '/aws/apigateway/${AWS::StackName}-access-logs'
  #     RetentionInDays: 30

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    # DependsOn:
    Properties:
      Name: !Sub '${AWS::StackName}-api-key'
      Description: API Key for protected endpoints
      Enabled: true

  # building in public, limit my exposure
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiGatewayStage
    Properties:
      UsagePlanName: !Sub '${AWS::StackName}-usage-plan'
      Description: Usage plan with throttling and quota limits
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref Environment
      Throttle:
        RateLimit: !Ref ThrottleRateLimit
        BurstLimit: !Ref ThrottleBurstLimit
      Quota:
        Limit: 5000  # 5k r/d
        Period: DAY

  # if key is leaked accidentally
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    # DependsOn:
    #   - ApiKey
    #   - UsagePlan

    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  ApiWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${AWS::StackName}-waf'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 1500  # 1500 r/5min for an IP
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
        
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
        
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSetMetric
      
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${AWS::StackName}-waf'

  ApiWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn:
      - ApiGatewayStage
    Properties:
      ResourceArn: !Sub 'arn:aws:apigateway:${AWS::Region}::/restapis/${ApiGateway}/stages/${Environment}'
      WebACLArn: !GetAtt ApiWebACL.Arn

  ApiGatewayIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /shared/api/gateway-id
      Type: String
      Value: !Ref ApiGateway

