AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy OAuth Setup 

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true # invite only
      UserPoolName: !Sub '${AWS::StackName}-users'
      UsernameAttributes:
        - email  
      AutoVerifiedAttributes:
        - email 
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT  
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: false
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false  # pub-client
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH  
        - ALLOW_REFRESH_TOKEN_AUTH 
        - ALLOW_USER_SRP_AUTH    

      AccessTokenValidity: 1 # hour
      IdTokenValidity: 1 # hour
      RefreshTokenValidity: 30 # days
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AllowedOAuthFlows:
        - code  
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:3000/callback  # local dev
        - https://franserr2288.github.io/lovelettertoLA/ # swap later
      LogoutURLs:
        - http://localhost:3000/  # local dev
        - https://franserr2288.github.io/lovelettertoLA/ # swap later
      SupportedIdentityProviders:
        - COGNITO  
  
  UserPoolIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /shared/cognito/user-pool-id
      Type: String
      Value: !Ref UserPool

  UserPoolArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /shared/cognito/user-pool-arn
      Type: String
      Value: !GetAtt UserPool.Arn

  UserPoolClientIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /shared/cognito/client-id
      Type: String
      Value: !Ref UserPoolClient