AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ingestion Components

Globals:
  Function:
    Layers:
      - '{{resolve:ssm:/shared/lib_layer}}'
    Timeout: 900

Resources:
  # SNAPSHOT
  SnapshotGeneratorDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SnapshotGenerator-DLQ
  
  SnapshotGeneratorQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SnapshotGeneratorQueue

      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SnapshotGeneratorDLQ.Arn
        maxReceiveCount: 2

  SnapshotGenerator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: snapshots/snapshot_generation.handler
      CodeUri: .
      Runtime: python3.12
      Role: "{{resolve:ssm:/ingestion/lambda-role}}"
      MemorySize: 1024
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:13
      Environment:
        Variables:
          BUCKET_NAME: "{{resolve:ssm:/shared/data-bucket-name}}"
          ENVIRONMENT: dev
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SnapshotGeneratorQueue.Arn
            BatchSize: 1

  # SNAPSHOT ROLLUP
  SnapshotRollUpQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SnapshotRollUpQueue-DLQ
  
  SnapshotRollUpQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SnapshotRollUpQueue

      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SnapshotRollUpQueueDLQ.Arn
        maxReceiveCount: 1

  SnapshotRollUp: 
    Type: AWS::Serverless::Function
    Properties:
      Handler: snapshots/snapshot_rollup.handler
      CodeUri: .
      Runtime: python3.12
      Role: "{{resolve:ssm:/ingestion/lambda-role}}"
      MemorySize: 1024
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:13
      Environment:
        Variables:
          BUCKET_NAME: "{{resolve:ssm:/shared/data-bucket-name}}"
          ENVIRONMENT: dev
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SnapshotRollUpQueue.Arn
            BatchSize: 1

  # ORCHESTRATOR
  ProcessingOrchestratorDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ProcessingOrchestrator-DLQ
  
  ProcessingOrchestrator:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ProcessingOrchestrator

      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessingOrchestratorDLQ.Arn
        maxReceiveCount: 1

  ProcessorOrchestrator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: orchestrator/fan_in.handler
      CodeUri: .
      Runtime: python3.12
      Role: "{{resolve:ssm:/ingestion/lambda-role}}"
      MemorySize: 512
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:13
      Environment:
        Variables:
          BUCKET_NAME: "{{resolve:ssm:/shared/data-bucket-name}}"
          SQS_QUEUE_NAME: !GetAtt ProcessingOrchestrator.QueueName
          # param it later
          ENVIRONMENT: dev

      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessingOrchestrator.Arn
            BatchSize: 1

  

        
              