AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR Repository for Lambda container images'

Resources:
  LambdaECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lovelettertola
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 7 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Value: !GetAtt LambdaECRRepository.RepositoryUri