AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ingestion Components

Globals:
  Function:
    Layers:
      - '{{resolve:ssm:/shared/lib_layer}}'

Resources:
  SocrataIngestionQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SocrataIngestionQueue-DLQ
  
  SocrataIngestionQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SocrataIngestionQueue

      VisibilityTimeout: 900
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SocrataIngestionQueueDLQ.Arn
        maxReceiveCount: 1
  
  SocrataIngestionQueueUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ingestion/queue_url
      Type: String
      Value: !Ref SocrataIngestionQueue
      Description: URL for the processing queue

  # Ingestion:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     PackageType: Image
  #     MemorySize: 3008
  #     Timeout: 900
  #     Role: "{{resolve:ssm:/ingestion/lambda-role}}"
  #     Environment:
  #       Variables:
  #         BASE_URL: "https://data.lacity.org"
  #         SOCRATA_TOKEN_PARAM_NAME: /ingestion/SOCRATA_APP_TOKEN
  #         BUCKET_NAME: "{{resolve:ssm:/shared/data-bucket-name}}"
  #         # param it later
  #         ENVIRONMENT: dev

  #     Events:
  #       SQSQueueEvent:
  #         Type: SQS
  #         Properties:
  #           Queue: !GetAtt SocrataIngestionQueue.Arn
  #           BatchSize: 1
  #   Metadata:
  #     DockerTag: python3.12-v2
  #     DockerContext: socrata/
  #     Dockerfile: Dockerfile

  Ingestion:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: .
      Handler: socrata/ingest.handler 
      MemorySize: 3008
      Timeout: 900
      Role: "{{resolve:ssm:/ingestion/lambda-role}}"
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:336392948345:layer:AWSSDKPandas-Python312:13
      Environment:
        Variables:
          BASE_URL: "https://data.lacity.org"
          SOCRATA_TOKEN_PARAM_NAME: /ingestion/SOCRATA_APP_TOKEN
          BUCKET_NAME: "{{resolve:ssm:/shared/data-bucket-name}}"
          ENVIRONMENT: dev
          REGION: !Sub ${AWS::Region}
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SocrataIngestionQueue.Arn
            BatchSize: 1

  DatasetIngestionOrchestrator:
    Type: AWS::Serverless::Function
    Properties:
      Handler: orchestrator/orchestrator.handler
      CodeUri: .
      Runtime: python3.12
      Role: "{{resolve:ssm:/ingestion/lambda-role}}"
      MemorySize: 128
      Events:
        # TimerCSV:
        #   Type: ScheduleV2
        #   Properties:
        #     ScheduleExpression: cron(0 12 * * ? *) # daily at 12pm UTC
        #     Input: !Sub '{"DATASET_NAME": "CITY311", "QUEUE_NAME":"${SocrataIngestionQueue.QueueName}", "DATASET_RESOURCE_ID":"h73f-gn57", "FORMAT": "CSV"}'
        #     RoleArn: "{{resolve:ssm:/ingestion/scheduler-role}}"
        TimerParquet:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(0 12 * * ? *) # daily at 12pm UTC
            Input: !Sub '{"DATASET_NAME": "City311", "QUEUE_NAME":"${SocrataIngestionQueue.QueueName}", "DATASET_RESOURCE_ID":"h73f-gn57", "FORMAT": "PARQUET", "PARTITION_COL":"cd"}'
            RoleArn: "{{resolve:ssm:/ingestion/scheduler-role}}"
        
              



  
    

      